### ISSUE TITLE
Column issues in property-details

### ISSUE THREAD

**Issue by pschneider87** [google/google-analytics-utilities#14]
Hi @b-kuehn, I discovered an issue I'd like to share.

The feature "list properties" will write the details of the selected properties into the sheet "GA4 Property Details" with **Data Retention Duration** & **Reset User Data on New Activity** in Columns Q and R

The "update" function though will use values from columns N (Service Level) and O (Number of Events Over the Past 7 Days) and thus fail.

![image](https://github.com/google/google-analytics-utilities/assets/17707309/e234aae1-2f47-41f2-bd3a-d34a402cc8c0)

With values for data retention in columns N and O it will work:
![image](https://github.com/google/google-analytics-utilities/assets/17707309/c5985c1a-9951-4176-b7fb-e467ddbecc0b)

**Comment by b-kuehn** [comment]
Hi,

Thanks for reporting this issue! I forgot to change the column numbers that were referenced in the "update" function for the data retention settings. This should now be fixed in the template sheet.

**Comment by pschneider87** [comment]
@b-kuehn I just checked with the latest version of your template sheet, and the error still seems to be there. Could you please have a look?

**Comment by pschneider87** [comment]
I guess you need to change in new_analytics/modifyGA4Entities as well:

` if (ga4Resource == 'properties') {
          responses.push(
            updateDataRetentionSettings(entity[16], entity[17],
            resourceName + '/dataRetentionSettings'));`
